### ISSUE TITLE
Suggestion: drop the "_rs" suffix from module name

### ISSUE THREAD

**Issue by ratijas** [Ayush1325/ki18n-rs#1]
We are already writing in Rust, no need to repeat. :)

```diff
- use ki18n_rs::KLocalizedContext;
+ use ki18n::KLocalizedContext;
```

**Comment by Ayush1325** [comment]
Ok, I had thought about it but kinda forgot to change that.

**Comment by Ayush1325** [comment]
Ok, so I have published the crate as ki18n and yanked all versions of ki18n-rs. This seems a bit of a hack, to be honest though and the old crate still seems to be visible on crates.io so I'm not completely sure if this was the correct solution. I guess I will try to get the old crate removed now.

**Comment by ratijas** [comment]
tbh, you didn't _have to_ to yank "-rs" crates, just change the usage/import path. But well, what's done is done :)

**Comment by Ayush1325** [comment]
@ratijas Sorry, I didn't know it was possible to do that. From what I found online, this seemed to be the only way to rename a crate.

**Comment by ratijas** [comment]
Oh wait, I didn't realize, https://crates.io/crates/qmetaobject doesn't have the suffix on crates.io either. Yeah, well, that's totally fine

**Comment by Ayush1325** [comment]
@ratijas Yeah, I only realized the qmeataobject thing after you opened the Issue too. 
Also, can you explain how it was possible to change the crate import name without changing the crate name? It might be useful in the future.

**Comment by ratijas** [comment]
I actually have no idea. As I said, I thought qmetaobject had the suffix, and Cargo.toml supposed to reference it with the suffix, but I was wrong.
